name: Auto Rebrand
on: workflow_dispatch
jobs:
  rebrand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change App Name
        run: |
          sed -i 's/>Sketchware Pro</>Pro App Builder</g' app/src/main/res/values/strings.xml
          sed -i 's/com.besome.sketch/com.sagir.proappbuilder/g' app/build.gradle
      - name: Save
        run: |
          git config user.email "sagir@test.com"
          git config user.name "Sagir"
          git add .
          git commit -m "renamed"
          git push
